enableGlobalCache: true
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
preferAggregateCacheInfo: true
yarnPath: .yarn/releases/yarn-3.0.0.cjs
nmHoistingLimits: workspaces
